### PR TITLE
Fix mixed content errors, load external assets over HTTPS

### PR DESCRIPTION
**Pull request by pwmarcz**

### CODE REVIEW

**Comment by pawelbx** [comment]
change it like this to work with both http and https:
http://blog.jonathanoliver.com/http-and-https-with-google-cdn/

**Comment by pawelbx** [comment]
I fixed the problem. Thanks for bringing it up.

**Comment by pwmarcz** [comment]
Sorry for not getting back earlier (and thanks for the fix!) But why not always load HTTPS?

The first Google result for "protocol-relative URLs" claims they shouldn't be used anymore: http://www.paulirish.com/2010/the-protocol-relative-url/

**Comment by pawelbx** [comment]
I didn't know this practice is now discouraged. Thanks for the link! I'll change the code.

**Pull request closed without merging**
